package com.smule.android.network.models;

public enum NotificationListItem$DetailedType {
    LOVE_SUPPRESSED,
    LOVE_NON_SUPPRESSED,
    FAVORITE_SUPPRESSED,
    FAVORITE_NON_SUPPRESSED,
    COMMENT_AGGREGATED,
    COMMENT_NON_AGGREGATED,
    MENTION_PERFORMANCE,
    MENTION_ACCOUNT,
    FOLLOW,
    INVITE,
    JOIN_GROUP,
    JOIN_DUET,
    FOLLOW_FB,
    CONNECT_FB,
    RENDER
}
